### ISSUE TITLE
Setting keyboard layout

### ISSUE THREAD

**Issue by TheBrainScrambler** [illiliti/tinyramfs#11]
Hello, I am currently using this for a basic encrypted kiss partition. I can actually boot the encrypted partition and I'm asked to enter my passphrase, but ... the entry is set to qwerty, and I have a different keyboard. I don't know much about disk encryption, I just know that on Arch Linux setting the keyboard layout is set by modifying /etc/mkinitcpio.conf, meaning that is it handled by the initramfs. Is it possible to do that with tinyramfs ?

**Comment by illiliti** [comment]
Yes, but not now. I have this feature in my TODO list. Should be easy to implement, i'll try

**Comment by TheBrainScrambler** [comment]
Oh right, it's in the TODO list. Let me know about it.
