### ISSUE TITLE
Can't create a file

### ISSUE THREAD

**Issue by tagirov** [illiliti/tinyramfs#15]
Hi!

Config:
```
monolith=0
hostonly=1
compress=gzip
root=/dev/mapper/cryptroot
hooks="luks eudev"
luks_name=cryptroot
luks_root=/dev/nvme0n1p2
luks_discard=1
```

Output:
```
~ # tinyramfs -o "/boot/initramfs-$(uname -r)"
>> preparing environment
>> preparing initramfs
>> running luks hook
```

**/boot/ is empty**

**Comment by illiliti** [comment]
> `monolith=0`

this is unnecessary

> hooks="luks eudev"

the order is incorrect. device manager must be always first

try again. if problem still persist, run tinyramfs with --debug and send me full log

**Comment by tagirov** [comment]
Wont work

Log:
[https://termbin.com/ualf](url)

**Comment by illiliti** [comment]
Fixed!
