### ISSUE TITLE
Add overlayfs support

### ISSUE THREAD

**Issue by eudaldgr** [illiliti/tinyramfs#16]
I'm unable to boot, due to `tinyramfs` don't mount overlayfs on init as it needs.

**Comment by eudaldgr** [comment]
I made a simple [sed](https://github.com/eudaldgr/kiss-live/blob/master/kiss-live#L160) modification to work, but it's only a dirty workaround.
Here, you can check my `tinyramfs` [config](https://github.com/eudaldgr/kiss-live/blob/master/files/config), and [hooks](https://github.com/eudaldgr/kiss-live/tree/master/hooks).
Note, that with this fs i don't need to point to a 'root=...' on the config, but without it won't boot.

**Comment by illiliti** [comment]
fixed. now you can specify `root` option to pseudofs. for example: `root=overlay`

**Comment by eudaldgr** [comment]
I did not explain very well, but you have understood it perfectly. :)
