### ISSUE TITLE
Too many levels of symbolic links

### ISSUE THREAD

**Issue by 0xbiel** [illiliti/tinyramfs#20]
Hi, when I run `tinyramfs -k 5.5.3 -o /boot/initrd` it returns:

```
-> preparing the environment
-> preparing initramfs
cp: failed to access '/tmp/tinyramfs.16615/lib/ld-linux-x86-64.so.2': Too many levels of symbolic links
``` 
Any idea of what could be causing this error?

**Comment by illiliti** [comment]
please run tinyramfs with --debug and provide full log

**Comment by 0xbiel** [comment]
oh i fixed it already, it was a wrong configuration on my system
