### ISSUE TITLE
Too many levels of symbolic links

### ISSUE THREAD

**Issue by quisys** [illiliti/tinyramfs#23]
When I run the command to install (`tinyramfs -o "/boot/initramfs-$(uname -r)"`), I get this error.

`cp: failed to access '/tmp/tinyramfs.5121/bin/env': Too many levels of symbolic links`

**Comment by quisys** [comment]
this was my fault.

**Comment by illiliti** [comment]
Can you explain what was that fault? Because there is already the same issue https://github.com/illiliti/tinyramfs/issues/20 and can't understand what caused it...
