### ISSUE TITLE
Project Name

### ISSUE THREAD

**Issue by muevoid** [illiliti/tinyramfs#3]
Hello! Firstly let me start by saying I absolutely love this project however I believe we could consider changing the name to make it easier to find and package. I have some ideas possibly if you would be willing to change it. Maybe lilinitramfs? or posinitramfs just something to give it a unique name. I understand if you would not like to change it at all just an idea.

EDIT: I may be stupid is tinyinitramfs the name if so should you change the repo name to that?

**Comment by illiliti** [comment]
Done

**Comment by muevoid** [comment]
Great! I appreciate it just was hard to find earlier while on github by just searching initramfs. This should help!
