### ISSUE TITLE
Cant stat '/lib//usr/lib/libc.so'

### ISSUE THREAD

**Issue by muevoid** [illiliti/tinyramfs#4]
Hello! This is my first time messing around with the initramfs on my personal machine. When running it with lvm and luks enabled I get that error. I also get the following two errors.

cp: can't create '/tmp/initramfs.31940/lib/modules/5.4.33-gnu/modules.builtin': Path does not exist

And

cp: can't create '/tmp/initramfs.31940/lib/modules/5.4.33-gnu/modules.dep': Path does not exist

EDIT: Last two errors were my mistake due to a monolithic kernel.

**Comment by illiliti** [comment]
Hmm, strange. Can you enable debug mode (--debug) and post output here?

**Comment by muevoid** [comment]
Here is the error link: https://termbin.com/hpg1


Or plain text:

+ trap '
        ret="$?"
        trap - EXIT INT
        [ "$debug" != 1 ] && remove_workdir
        [ "$ret"   != 0 ] && [ "$panic" != 1 ] && panic "something went wrong"
        ' EXIT INT
+ create_structure
+ info 'creating directory structure'
+ printf 'info >> %s\n' 'creating directory structure'
+ mkdir -p /tmp/initramfs.29303/etc /tmp/initramfs.29303/dev /tmp/initramfs.29303/sys /tmp/initramfs.29303/tmp /tmp/initramfs.29303/proc /tmp/initramfs.29303/root /tmp/initramfs.29303/usr/lib /tmp/initramfs.29303/usr/bin /tmp/initramfs.29303/mnt/root
+ create_symlinks
+ info 'creating symlinks'
+ printf 'info >> %s\n' 'creating symlinks'
+ ln -s usr/lib /tmp/initramfs.29303/lib
+ ln -s usr/lib /tmp/initramfs.29303/lib64
+ ln -s usr/bin /tmp/initramfs.29303/bin
+ ln -s usr/bin /tmp/initramfs.29303/sbin
+ ln -s bin /tmp/initramfs.29303/usr/sbin
+ ln -s lib /tmp/initramfs.29303/usr/lib64
+ '[' 1 '=' 1 ]
+ install_lvm
+ info 'installing LVM'
+ printf 'info >> %s\n' 'installing LVM'
+ install_binary lvchange
+ command -v lvchange
+ binary=/usr/bin/lvchange
+ : no operation
+ '[' -e /tmp/initramfs.29303/usr/bin/lvchange ]
+ '[' -h /usr/bin/lvchange ]
+ cp -P /usr/bin/lvchange /tmp/initramfs.29303/usr/bin/
+ readlink /usr/bin/lvchange
+ binary=/usr/bin/lvm
+ '[' -h /usr/bin/lvm ]
+ install -m755 /usr/bin/lvm /tmp/initramfs.29303/usr/bin/lvm
+ strip /tmp/initramfs.29303/usr/bin/lvm
+ ldd /usr/bin/lvm
+ read -r _library
+ ldd /usr/bin/lvm
+ _library='/lib/ld-musl-x86_64.so.1 (0x7f0a5d686000)'
+ _library='/lib/ld-musl-x86_64.so.1 (0x7f0a5d686000)'
+ _library=/lib/ld-musl-x86_64.so.1
+ '[' -e /lib/ld-musl-x86_64.so.1 ]
+ install_library /lib/ld-musl-x86_64.so.1
+ library=/lib/ld-musl-x86_64.so.1
+ '[' -e /tmp/initramfs.29303/usr/lib/ld-musl-x86_64.so.1 ]
+ '[' -h /lib/ld-musl-x86_64.so.1 ]
+ cp -P /lib/ld-musl-x86_64.so.1 /tmp/initramfs.29303/usr/lib/
+ readlink /lib/ld-musl-x86_64.so.1
+ library=/lib//usr/lib/libc.so
+ '[' -h /lib//usr/lib/libc.so ]
+ install -m755 /lib//usr/lib/libc.so /tmp/initramfs.29303/usr/lib/libc.so
install: can't stat '/lib//usr/lib/libc.so': No such file or directory
+ strip /tmp/initramfs.29303/usr/lib/libc.so
+ :
+ read -r _library
+ _library='libdevmapper-event.so.1.02 => /lib/libdevmapper-event.so.1.02 (0x7f0a5d217000)'
+ _library='/lib/libdevmapper-event.so.1.02 (0x7f0a5d217000)'
+ _library=/lib/libdevmapper-event.so.1.02
+ '[' -e /lib/libdevmapper-event.so.1.02 ]
+ install_library /lib/libdevmapper-event.so.1.02
+ library=/lib/libdevmapper-event.so.1.02
+ '[' -e /tmp/initramfs.29303/usr/lib/libdevmapper-event.so.1.02 ]
+ '[' -h /lib/libdevmapper-event.so.1.02 ]
+ install -m755 /lib/libdevmapper-event.so.1.02 /tmp/initramfs.29303/usr/lib/libdevmapper-event.so.1.02
+ strip /tmp/initramfs.29303/usr/lib/libdevmapper-event.so.1.02
+ read -r _library
+ _library='libdevmapper.so.1.02 => /lib/libdevmapper.so.1.02 (0x7f0a5d1c8000)'
+ _library='/lib/libdevmapper.so.1.02 (0x7f0a5d1c8000)'
+ _library=/lib/libdevmapper.so.1.02
+ '[' -e /lib/libdevmapper.so.1.02 ]
+ install_library /lib/libdevmapper.so.1.02
+ library=/lib/libdevmapper.so.1.02
+ '[' -e /tmp/initramfs.29303/usr/lib/libdevmapper.so.1.02 ]
+ '[' -h /lib/libdevmapper.so.1.02 ]
+ install -m755 /lib/libdevmapper.so.1.02 /tmp/initramfs.29303/usr/lib/libdevmapper.so.1.02
+ strip /tmp/initramfs.29303/usr/lib/libdevmapper.so.1.02
+ read -r _library
+ _library='libudev.so.1 => /lib/libudev.so.1 (0x7f0a5d1a6000)'
+ _library='/lib/libudev.so.1 (0x7f0a5d1a6000)'
+ _library=/lib/libudev.so.1
+ '[' -e /lib/libudev.so.1 ]
+ install_library /lib/libudev.so.1
+ library=/lib/libudev.so.1
+ '[' -e /tmp/initramfs.29303/usr/lib/libudev.so.1 ]
+ '[' -h /lib/libudev.so.1 ]
+ cp -P /lib/libudev.so.1 /tmp/initramfs.29303/usr/lib/
+ readlink /lib/libudev.so.1
+ library=/lib/libudev.so.1.6.3
+ '[' -h /lib/libudev.so.1.6.3 ]
+ install -m755 /lib/libudev.so.1.6.3 /tmp/initramfs.29303/usr/lib/libudev.so.1.6.3
+ strip /tmp/initramfs.29303/usr/lib/libudev.so.1.6.3
+ read -r _library
+ _library='libblkid.so.1 => /lib/libblkid.so.1 (0x7f0a5d15f000)'
+ _library='/lib/libblkid.so.1 (0x7f0a5d15f000)'
+ _library=/lib/libblkid.so.1
+ '[' -e /lib/libblkid.so.1 ]
+ install_library /lib/libblkid.so.1
+ library=/lib/libblkid.so.1
+ '[' -e /tmp/initramfs.29303/usr/lib/libblkid.so.1 ]
+ '[' -h /lib/libblkid.so.1 ]
+ cp -P /lib/libblkid.so.1 /tmp/initramfs.29303/usr/lib/
+ readlink /lib/libblkid.so.1
+ library=/lib/libblkid.so.1.1.0
+ '[' -h /lib/libblkid.so.1.1.0 ]
+ install -m755 /lib/libblkid.so.1.1.0 /tmp/initramfs.29303/usr/lib/libblkid.so.1.1.0
+ strip /tmp/initramfs.29303/usr/lib/libblkid.so.1.1.0
+ read -r _library
+ _library='libaio.so.1 => /lib/libaio.so.1 (0x7f0a5d15a000)'
+ _library='/lib/libaio.so.1 (0x7f0a5d15a000)'
+ _library=/lib/libaio.so.1
+ '[' -e /lib/libaio.so.1 ]
+ install_library /lib/libaio.so.1
+ library=/lib/libaio.so.1
+ '[' -e /tmp/initramfs.29303/usr/lib/libaio.so.1 ]
+ '[' -h /lib/libaio.so.1 ]
+ cp -P /lib/libaio.so.1 /tmp/initramfs.29303/usr/lib/
+ readlink /lib/libaio.so.1
+ library=/lib/libaio.so.1.0.1
+ '[' -h /lib/libaio.so.1.0.1 ]
+ install -m755 /lib/libaio.so.1.0.1 /tmp/initramfs.29303/usr/lib/libaio.so.1.0.1
+ strip /tmp/initramfs.29303/usr/lib/libaio.so.1.0.1
+ read -r _library
+ _library='libc.so => /lib/ld-musl-x86_64.so.1 (0x7f0a5d686000)'
+ _library='/lib/ld-musl-x86_64.so.1 (0x7f0a5d686000)'
+ _library=/lib/ld-musl-x86_64.so.1
+ '[' -e /lib/ld-musl-x86_64.so.1 ]
+ install_library /lib/ld-musl-x86_64.so.1
+ library=/lib/ld-musl-x86_64.so.1
+ '[' -e /tmp/initramfs.29303/usr/lib/ld-musl-x86_64.so.1 ]
+ return
+ read -r _library
+ '['  ]
+ install_binary vgchange
+ command -v vgchange
+ binary=/usr/bin/vgchange
+ : no operation
+ '[' -e /tmp/initramfs.29303/usr/bin/vgchange ]
+ '[' -h /usr/bin/vgchange ]
+ cp -P /usr/bin/vgchange /tmp/initramfs.29303/usr/bin/
+ readlink /usr/bin/vgchange
+ binary=/usr/bin/lvm
+ '[' -h /usr/bin/lvm ]
+ install -m755 /usr/bin/lvm /tmp/initramfs.29303/usr/bin/lvm
+ strip /tmp/initramfs.29303/usr/bin/lvm
+ ldd /usr/bin/lvm
+ ldd /usr/bin/lvm
+ read -r _library
+ _library='/lib/ld-musl-x86_64.so.1 (0x7f6cf5873000)'
+ _library='/lib/ld-musl-x86_64.so.1 (0x7f6cf5873000)'
+ _library=/lib/ld-musl-x86_64.so.1
+ '[' -e /lib/ld-musl-x86_64.so.1 ]
+ install_library /lib/ld-musl-x86_64.so.1
+ library=/lib/ld-musl-x86_64.so.1
+ '[' -e /tmp/initramfs.29303/usr/lib/ld-musl-x86_64.so.1 ]
+ return
+ read -r _library
+ _library='libdevmapper-event.so.1.02 => /lib/libdevmapper-event.so.1.02 (0x7f6cf5404000)'
+ _library='/lib/libdevmapper-event.so.1.02 (0x7f6cf5404000)'
+ _library=/lib/libdevmapper-event.so.1.02
+ '[' -e /lib/libdevmapper-event.so.1.02 ]
+ install_library /lib/libdevmapper-event.so.1.02
+ library=/lib/libdevmapper-event.so.1.02
+ '[' -e /tmp/initramfs.29303/usr/lib/libdevmapper-event.so.1.02 ]
+ return
+ read -r _library
+ _library='libdevmapper.so.1.02 => /lib/libdevmapper.so.1.02 (0x7f6cf53b5000)'
+ _library='/lib/libdevmapper.so.1.02 (0x7f6cf53b5000)'
+ _library=/lib/libdevmapper.so.1.02
+ '[' -e /lib/libdevmapper.so.1.02 ]
+ install_library /lib/libdevmapper.so.1.02
+ library=/lib/libdevmapper.so.1.02
+ '[' -e /tmp/initramfs.29303/usr/lib/libdevmapper.so.1.02 ]
+ return
+ read -r _library
+ _library='libudev.so.1 => /lib/libudev.so.1 (0x7f6cf5393000)'
+ _library='/lib/libudev.so.1 (0x7f6cf5393000)'
+ _library=/lib/libudev.so.1
+ '[' -e /lib/libudev.so.1 ]
+ install_library /lib/libudev.so.1
+ library=/lib/libudev.so.1
+ '[' -e /tmp/initramfs.29303/usr/lib/libudev.so.1 ]
+ return
+ read -r _library
+ _library='libblkid.so.1 => /lib/libblkid.so.1 (0x7f6cf534c000)'
+ _library='/lib/libblkid.so.1 (0x7f6cf534c000)'
+ _library=/lib/libblkid.so.1
+ '[' -e /lib/libblkid.so.1 ]
+ install_library /lib/libblkid.so.1
+ library=/lib/libblkid.so.1
+ '[' -e /tmp/initramfs.29303/usr/lib/libblkid.so.1 ]
+ return
+ read -r _library
+ _library='libaio.so.1 => /lib/libaio.so.1 (0x7f6cf5347000)'
+ _library='/lib/libaio.so.1 (0x7f6cf5347000)'
+ _library=/lib/libaio.so.1
+ '[' -e /lib/libaio.so.1 ]
+ install_library /lib/libaio.so.1
+ library=/lib/libaio.so.1
+ '[' -e /tmp/initramfs.29303/usr/lib/libaio.so.1 ]
+ return
+ read -r _library
+ _library='libc.so => /lib/ld-musl-x86_64.so.1 (0x7f6cf5873000)'
+ _library='/lib/ld-musl-x86_64.so.1 (0x7f6cf5873000)'
+ _library=/lib/ld-musl-x86_64.so.1
+ '[' -e /lib/ld-musl-x86_64.so.1 ]
+ install_library /lib/ld-musl-x86_64.so.1
+ library=/lib/ld-musl-x86_64.so.1
+ '[' -e /tmp/initramfs.29303/usr/lib/ld-musl-x86_64.so.1 ]
+ return
+ read -r _library
+ '['  ]
+ lvm_config='
        devices {
            write_cache_state = 0
        }
        backup {
            backup  = 0
            archive = 0
        }
        global {
            use_lvmetad = 0
        }'
+ IFS=,
+ set --
+ IFS=' 	
'
+ mkdir -p /tmp/initramfs.29303/etc/lvm
+ lvmconfig --config '
        devices {
            write_cache_state = 0
        }
        backup {
            backup  = 0
            archive = 0
        }
        global {
            use_lvmetad = 0
        }'
+ printf '%s\n' 'lvm=1' 'lvm_opts='
+ '[' 1 '=' 1 ]
+ install_luks
+ info 'installing LUKS'
+ printf 'info >> %s\n' 'installing LUKS'
+ install_binary cryptsetup
+ command -v cryptsetup
+ binary=/usr/bin/cryptsetup
+ : no operation
+ '[' -e /tmp/initramfs.29303/usr/bin/cryptsetup ]
+ '[' -h /usr/bin/cryptsetup ]
+ install -m755 /usr/bin/cryptsetup /tmp/initramfs.29303/usr/bin/cryptsetup
+ strip /tmp/initramfs.29303/usr/bin/cryptsetup
+ ldd /usr/bin/cryptsetup
+ ldd /usr/bin/cryptsetup
+ read -r _library
+ _library='/lib/ld-musl-x86_64.so.1 (0x7f6d04cd5000)'
+ _library='/lib/ld-musl-x86_64.so.1 (0x7f6d04cd5000)'
+ _library=/lib/ld-musl-x86_64.so.1
+ '[' -e /lib/ld-musl-x86_64.so.1 ]
+ install_library /lib/ld-musl-x86_64.so.1
+ library=/lib/ld-musl-x86_64.so.1
+ '[' -e /tmp/initramfs.29303/usr/lib/ld-musl-x86_64.so.1 ]
+ return
+ read -r _library
+ _library='libcryptsetup.so.12 => /lib/libcryptsetup.so.12 (0x7f6d04c4f000)'
+ _library='/lib/libcryptsetup.so.12 (0x7f6d04c4f000)'
+ _library=/lib/libcryptsetup.so.12
+ '[' -e /lib/libcryptsetup.so.12 ]
+ install_library /lib/libcryptsetup.so.12
+ library=/lib/libcryptsetup.so.12
+ '[' -e /tmp/initramfs.29303/usr/lib/libcryptsetup.so.12 ]
+ '[' -h /lib/libcryptsetup.so.12 ]
+ cp -P /lib/libcryptsetup.so.12 /tmp/initramfs.29303/usr/lib/
+ readlink /lib/libcryptsetup.so.12
+ library=/lib/libcryptsetup.so.12.6.0
+ '[' -h /lib/libcryptsetup.so.12.6.0 ]
+ install -m755 /lib/libcryptsetup.so.12.6.0 /tmp/initramfs.29303/usr/lib/libcryptsetup.so.12.6.0
+ strip /tmp/initramfs.29303/usr/lib/libcryptsetup.so.12.6.0
+ read -r _library
+ _library='libpopt.so.0 => /lib/libpopt.so.0 (0x7f6d04c42000)'
+ _library='/lib/libpopt.so.0 (0x7f6d04c42000)'
+ _library=/lib/libpopt.so.0
+ '[' -e /lib/libpopt.so.0 ]
+ install_library /lib/libpopt.so.0
+ library=/lib/libpopt.so.0
+ '[' -e /tmp/initramfs.29303/usr/lib/libpopt.so.0 ]
+ '[' -h /lib/libpopt.so.0 ]
+ cp -P /lib/libpopt.so.0 /tmp/initramfs.29303/usr/lib/
+ readlink /lib/libpopt.so.0
+ library=/lib/libpopt.so.0.0.0
+ '[' -h /lib/libpopt.so.0.0.0 ]
+ install -m755 /lib/libpopt.so.0.0.0 /tmp/initramfs.29303/usr/lib/libpopt.so.0.0.0
+ strip /tmp/initramfs.29303/usr/lib/libpopt.so.0.0.0
+ read -r _library
+ _library='libuuid.so.1 => /lib/libuuid.so.1 (0x7f6d04c39000)'
+ _library='/lib/libuuid.so.1 (0x7f6d04c39000)'
+ _library=/lib/libuuid.so.1
+ '[' -e /lib/libuuid.so.1 ]
+ install_library /lib/libuuid.so.1
+ library=/lib/libuuid.so.1
+ '[' -e /tmp/initramfs.29303/usr/lib/libuuid.so.1 ]
+ '[' -h /lib/libuuid.so.1 ]
+ cp -P /lib/libuuid.so.1 /tmp/initramfs.29303/usr/lib/
+ readlink /lib/libuuid.so.1
+ library=/lib/libuuid.so.1.3.0
+ '[' -h /lib/libuuid.so.1.3.0 ]
+ install -m755 /lib/libuuid.so.1.3.0 /tmp/initramfs.29303/usr/lib/libuuid.so.1.3.0
+ strip /tmp/initramfs.29303/usr/lib/libuuid.so.1.3.0
+ read -r _library
+ _library='libc.so => /lib/ld-musl-x86_64.so.1 (0x7f6d04cd5000)'
+ _library='/lib/ld-musl-x86_64.so.1 (0x7f6d04cd5000)'
+ _library=/lib/ld-musl-x86_64.so.1
+ '[' -e /lib/ld-musl-x86_64.so.1 ]
+ install_library /lib/ld-musl-x86_64.so.1
+ library=/lib/ld-musl-x86_64.so.1
+ '[' -e /tmp/initramfs.29303/usr/lib/ld-musl-x86_64.so.1 ]
+ return
+ read -r _library
+ _library='libdevmapper.so.1.02 => /lib/libdevmapper.so.1.02 (0x7f6d04bea000)'
+ _library='/lib/libdevmapper.so.1.02 (0x7f6d04bea000)'
+ _library=/lib/libdevmapper.so.1.02
+ '[' -e /lib/libdevmapper.so.1.02 ]
+ install_library /lib/libdevmapper.so.1.02
+ library=/lib/libdevmapper.so.1.02
+ '[' -e /tmp/initramfs.29303/usr/lib/libdevmapper.so.1.02 ]
+ return
+ read -r _library
+ _library='libssl.so.47 => /lib/libssl.so.47 (0x7f6d04b98000)'
+ _library='/lib/libssl.so.47 (0x7f6d04b98000)'
+ _library=/lib/libssl.so.47
+ '[' -e /lib/libssl.so.47 ]
+ install_library /lib/libssl.so.47
+ library=/lib/libssl.so.47
+ '[' -e /tmp/initramfs.29303/usr/lib/libssl.so.47 ]
+ '[' -h /lib/libssl.so.47 ]
+ cp -P /lib/libssl.so.47 /tmp/initramfs.29303/usr/lib/
+ readlink /lib/libssl.so.47
+ library=/lib/libssl.so.47.0.6
+ '[' -h /lib/libssl.so.47.0.6 ]
+ install -m755 /lib/libssl.so.47.0.6 /tmp/initramfs.29303/usr/lib/libssl.so.47.0.6
+ strip /tmp/initramfs.29303/usr/lib/libssl.so.47.0.6
+ read -r _library
+ _library='libcrypto.so.45 => /lib/libcrypto.so.45 (0x7f6d049e2000)'
+ _library='/lib/libcrypto.so.45 (0x7f6d049e2000)'
+ _library=/lib/libcrypto.so.45
+ '[' -e /lib/libcrypto.so.45 ]
+ install_library /lib/libcrypto.so.45
+ library=/lib/libcrypto.so.45
+ '[' -e /tmp/initramfs.29303/usr/lib/libcrypto.so.45 ]
+ '[' -h /lib/libcrypto.so.45 ]
+ cp -P /lib/libcrypto.so.45 /tmp/initramfs.29303/usr/lib/
+ readlink /lib/libcrypto.so.45
+ library=/lib/libcrypto.so.45.0.5
+ '[' -h /lib/libcrypto.so.45.0.5 ]
+ install -m755 /lib/libcrypto.so.45.0.5 /tmp/initramfs.29303/usr/lib/libcrypto.so.45.0.5
+ strip /tmp/initramfs.29303/usr/lib/libcrypto.so.45.0.5
+ read -r _library
+ _library='libjson-c.so.4 => /lib/libjson-c.so.4 (0x7f6d049d3000)'
+ _library='/lib/libjson-c.so.4 (0x7f6d049d3000)'
+ _library=/lib/libjson-c.so.4
+ '[' -e /lib/libjson-c.so.4 ]
+ install_library /lib/libjson-c.so.4
+ library=/lib/libjson-c.so.4
+ '[' -e /tmp/initramfs.29303/usr/lib/libjson-c.so.4 ]
+ '[' -h /lib/libjson-c.so.4 ]
+ cp -P /lib/libjson-c.so.4 /tmp/initramfs.29303/usr/lib/
+ readlink /lib/libjson-c.so.4
+ library=/lib/libjson-c.so.4.0.0
+ '[' -h /lib/libjson-c.so.4.0.0 ]
+ install -m755 /lib/libjson-c.so.4.0.0 /tmp/initramfs.29303/usr/lib/libjson-c.so.4.0.0
+ strip /tmp/initramfs.29303/usr/lib/libjson-c.so.4.0.0
+ read -r _library
+ _library='libudev.so.1 => /lib/libudev.so.1 (0x7f6d049b1000)'
+ _library='/lib/libudev.so.1 (0x7f6d049b1000)'
+ _library=/lib/libudev.so.1
+ '[' -e /lib/libudev.so.1 ]
+ install_library /lib/libudev.so.1
+ library=/lib/libudev.so.1
+ '[' -e /tmp/initramfs.29303/usr/lib/libudev.so.1 ]
+ return
+ read -r _library
+ _library='libblkid.so.1 => /lib/libblkid.so.1 (0x7f6d0496a000)'
+ _library='/lib/libblkid.so.1 (0x7f6d0496a000)'
+ _library=/lib/libblkid.so.1
+ '[' -e /lib/libblkid.so.1 ]
+ install_library /lib/libblkid.so.1
+ library=/lib/libblkid.so.1
+ '[' -e /tmp/initramfs.29303/usr/lib/libblkid.so.1 ]
+ return
+ read -r _library
+ '['  ]
+ '[' -e /usr/lib/libgcc_s.so.1 ]
+ install_library /usr/lib/libgcc_s.so.1
+ library=/usr/lib/libgcc_s.so.1
+ '[' -e /tmp/initramfs.29303/usr/lib/libgcc_s.so.1 ]
+ '[' -h /usr/lib/libgcc_s.so.1 ]
+ install -m755 /usr/lib/libgcc_s.so.1 /tmp/initramfs.29303/usr/lib/libgcc_s.so.1
+ strip /tmp/initramfs.29303/usr/lib/libgcc_s.so.1
+ IFS=,
+ set -- 'discard=1' 'name=luks'
+ IFS=' 	
'
+ printf '%s\n' 'luks=1' 'luks_root=/dev/sda2' 'luks_opts=discard=1,name=luks'
+ '[' 1 '!=' 1 ]
+ install_devmgr
+ info 'installing device manager'
+ printf 'info >> %s\n' 'installing device manager'
+ install_requirements
+ info 'installing requirements'
+ printf 'info >> %s\n' 'installing requirements'
+ install_binary '['
+ command -v '['
+ binary='['
+ IFS=:
+ set -- /usr/local/sbin /usr/local/bin /usr/bin /usr/sbin /sbin /bin
+ IFS=' 	
'
+ '[' -x '/usr/local/sbin/[' ]
+ '[' -x '/usr/local/bin/[' ]
+ '[' -x '/usr/bin/[' ]
+ binary='/usr/bin/['
+ break
+ '[' -e '/tmp/initramfs.29303/usr/bin/[' ]
+ '[' -h '/usr/bin/[' ]
+ cp -P '/usr/bin/[' /tmp/initramfs.29303/usr/bin/
+ readlink '/usr/bin/['
+ binary=/usr/bin/busybox
+ '[' -h /usr/bin/busybox ]
+ install -m755 /usr/bin/busybox /tmp/initramfs.29303/usr/bin/busybox
+ strip /tmp/initramfs.29303/usr/bin/busybox
+ ldd /usr/bin/busybox
+ return 0
+ install_binary sh
+ command -v sh
+ binary=/usr/bin/sh
+ : no operation
+ '[' -e /tmp/initramfs.29303/usr/bin/sh ]
+ '[' -h /usr/bin/sh ]
+ cp -P /usr/bin/sh /tmp/initramfs.29303/usr/bin/
+ readlink /usr/bin/sh
+ binary=/usr/bin/busybox
+ '[' -h /usr/bin/busybox ]
+ install -m755 /usr/bin/busybox /tmp/initramfs.29303/usr/bin/busybox
+ strip /tmp/initramfs.29303/usr/bin/busybox
+ ldd /usr/bin/busybox
+ return 0
+ install_binary sleep
+ command -v sleep
+ binary=/usr/bin/sleep
+ : no operation
+ '[' -e /tmp/initramfs.29303/usr/bin/sleep ]
+ '[' -h /usr/bin/sleep ]
+ cp -P /usr/bin/sleep /tmp/initramfs.29303/usr/bin/
+ readlink /usr/bin/sleep
+ binary=/usr/bin/busybox
+ '[' -h /usr/bin/busybox ]
+ install -m755 /usr/bin/busybox /tmp/initramfs.29303/usr/bin/busybox
+ strip /tmp/initramfs.29303/usr/bin/busybox
+ ldd /usr/bin/busybox
+ return 0
+ install_binary mount
+ command -v mount
+ binary=/usr/bin/mount
+ : no operation
+ '[' -e /tmp/initramfs.29303/usr/bin/mount ]
+ '[' -h /usr/bin/mount ]
+ cp -P /usr/bin/mount /tmp/initramfs.29303/usr/bin/
+ readlink /usr/bin/mount
+ binary=/usr/bin/busybox
+ '[' -h /usr/bin/busybox ]
+ install -m755 /usr/bin/busybox /tmp/initramfs.29303/usr/bin/busybox
+ strip /tmp/initramfs.29303/usr/bin/busybox
+ ldd /usr/bin/busybox
+ return 0
+ install_binary printf
+ command -v printf
+ binary=printf
+ IFS=:
+ set -- /usr/local/sbin /usr/local/bin /usr/bin /usr/sbin /sbin /bin
+ IFS=' 	
'
+ '[' -x /usr/local/sbin/printf ]
+ '[' -x /usr/local/bin/printf ]
+ '[' -x /usr/bin/printf ]
+ binary=/usr/bin/printf
+ break
+ '[' -e /tmp/initramfs.29303/usr/bin/printf ]
+ '[' -h /usr/bin/printf ]
+ cp -P /usr/bin/printf /tmp/initramfs.29303/usr/bin/
+ readlink /usr/bin/printf
+ binary=/usr/bin/busybox
+ '[' -h /usr/bin/busybox ]
+ install -m755 /usr/bin/busybox /tmp/initramfs.29303/usr/bin/busybox
+ strip /tmp/initramfs.29303/usr/bin/busybox
+ ldd /usr/bin/busybox
+ return 0
+ install_binary setsid
+ command -v setsid
+ binary=/usr/bin/setsid
+ : no operation
+ '[' -e /tmp/initramfs.29303/usr/bin/setsid ]
+ '[' -h /usr/bin/setsid ]
+ cp -P /usr/bin/setsid /tmp/initramfs.29303/usr/bin/
+ readlink /usr/bin/setsid
+ binary=/usr/bin/busybox
+ '[' -h /usr/bin/busybox ]
+ install -m755 /usr/bin/busybox /tmp/initramfs.29303/usr/bin/busybox
+ strip /tmp/initramfs.29303/usr/bin/busybox
+ ldd /usr/bin/busybox
+ return 0
+ install_binary switch_root
+ command -v switch_root
+ binary=/usr/bin/switch_root
+ : no operation
+ '[' -e /tmp/initramfs.29303/usr/bin/switch_root ]
+ '[' -h /usr/bin/switch_root ]
+ cp -P /usr/bin/switch_root /tmp/initramfs.29303/usr/bin/
+ readlink /usr/bin/switch_root
+ binary=/usr/bin/busybox
+ '[' -h /usr/bin/busybox ]
+ install -m755 /usr/bin/busybox /tmp/initramfs.29303/usr/bin/busybox
+ strip /tmp/initramfs.29303/usr/bin/busybox
+ ldd /usr/bin/busybox
+ return 0
+ install -m755 /usr/share/tinyramfs/init /tmp/initramfs.29303/init
+ printf '%s\n' 'root=' 'root_type=' 'root_opts=' 'devmgr=' 'monolith=1'
+ create_initramfs
+ info 'creating initramfs image'
+ printf 'info >> %s\n' 'creating initramfs image'
+ '[' 0 '!=' 1 ]
+ '[' -e /boot/tinyramfs-5.4.33.img ]
+ panic 'initramfs image already exist'
+ printf 'panic >> %s\n' 'initramfs image already exist'
panic >> initramfs image already exist
+ panic=1
+ exit 1
+ ret=1
+ trap - EXIT INT
+ '[' 1 '!=' 1 ]
+ '[' 1 '!=' 0 ]
+ '[' 1 '!=' 1 ]

**Comment by muevoid** [comment]
I just noticed it still created an initramfs despite that error. I will attempt booting with it.

After doing that I get another error from the init file saying line 67 ln: not found then ends in kernel panic.

**Comment by illiliti** [comment]
Fixed

**Comment by muevoid** [comment]
Kk testing right now

**Comment by muevoid** [comment]
Closer however now I recieve an error saying panic >> failed to lookup parition after typing in my passphrase it hangs for roughly 10 seconds before this. Then states sh: cant access tty; job control turned off. FYI I do have a second grub menu entry with better initramfs currently so I do have a working pc it would be nice to switch to this though.

**Comment by illiliti** [comment]
Which device manager do you use? (mdev,mdev,udev) Looks like decryption process is very slow, so that caused 'failed to lookup partition'. I can increase delay if that's root of problem

**Comment by muevoid** [comment]
I use eudev currently

**Comment by illiliti** [comment]
I have increased delay to 80

**Comment by muevoid** [comment]
Same error unfortunately

**Comment by illiliti** [comment]
Are you sure that your config correct?

**Comment by muevoid** [comment]
Im pretty sure. Here it is:
#
# configuration
#

# debug mode
#
debug=0

# overwrite initramfs
#
force=0

# initramfs output path
#
# default - /tmp/initramfs-$kernel
# example - output="/tmp/myinitramfs.img.gz"
#
output="/boot/tinyramfs-5.4.33.img"

# monolithic kernel
#
monolith=1

# modules directory
#
# default - /lib/modules
# example - moddir="/mnt/root/lib/modules"
#
moddir=""

# kernel version
#
# default - $(uname -r)
# example - kernel="5.4.18_1"
#
kernel=""

# compression program
#
# default - gzip -9
# example - compress="pigz -9"
#
compress=""

# root
#
# supported - PARTUUID, DEVICE, LABEL, UUID
# example -
#   root="/dev/sda1"
#   root="PARTUUID=35f923c5-083a-4950-a4da-e611d0778121"
#
root="/dev/mapper/vg-root"

# root type
#
# default - autodetected
# example - root_type="btrfs"
#
root_type=""

# root options
# example - see fstab(5)
#
root_opts=""

# device manager
# supported - udev, mdev, mdevd
#
devmgr="udev"

# hostonly mode
#
hostonly=0

# additional modules
# example - modules="fat crc32c_generic"
#
modules=""

# exclude modules
# example - modules_exclude="wmi fuse"
#
modules_exclude=""

# additional binaries
# example - binaries="ls cat /path/to/mycustomprog"
#
binaries=""

# LVM support
#
lvm=1

# LVM options
#
# supported - tag, name, group, config, discard
# description -
#   tag - trigger lvm by tag
#   name - trigger lvm by logical volume name
#   group - trigger lvm by volume group name
#   config - embed host lvm config
#   discard - enable issue_discards
# example -
#   lvm_opts="tag=lvm-server"
#   lvm_opts="name=lv1,group=vg1"
#   lvm_opts="config=1,discard"
#   lvm_opts="discard=1"
#
lvm_opts="discard=1"

# LUKS support
#
luks=1

# LUKS encrypted root
#
# supported - PARTUUID, DEVICE, LABEL, UUID
# example -
#   luks_root="/dev/sda1"
#   luks_root="PARTUUID=35f923c5-083a-4950-a4da-e611d0778121"
#
luks_root="/dev/sda2"

# LUKS options
#
# supported - key, name, header, discard
# description -
#   key - embed key
#   name - device mapper name
#   header - embed header
#   discard - enable allow-discards
# example -
#luks_opts="key=/path/to/keyfile,name=myluksroot,header=/path/to/header,discard"
#   luks_opts="discard=1"
#
luks_opts="discard=1,name=luks"

**Comment by illiliti** [comment]
Try to use UUID or PARTUUID instead of /dev/

**Comment by muevoid** [comment]
Kk ill try that out tommorow unfortunately dont have any more time to debug currently thanks for all the help so far!

**Comment by illiliti** [comment]
Fine, glad to help either way. I'll leave it open until your issues being fixed

**Comment by illiliti** [comment]
I think i figured out what caused it. Fix pushed

**Comment by muevoid** [comment]
Yep that worked! Thank you so much for the help Im going to do more testing with some different configurations to make sure everything still works out but this is very promising!
