### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by muevoid** [illiliti/tinyramfs#5]
I am working on packaging this for KISS linux and sumbiting it to the community repo. However I cannot find what version it is on could we add that to the Readme or a seperate version file?

**Comment by eudaldgr** [comment]
I packaged `tinyramfs` on my own repo. See here [kiss-garbage](https://github.com/eudaldgr/kiss-garbage/tree/master/tinyramfs).

**Comment by muevoid** [comment]
Oh awesome! Ill close this issue then.

**Comment by illiliti** [comment]
I'll do release when i'll be sure that tinyramfs is stable
