### ISSUE TITLE
Hanging

### ISSUE THREAD

**Issue by muevoid** [illiliti/tinyramfs#6]
Unfortunately after typing my passphrase it appears to hang. Any help would be appeciated. My system is fully updated. I only use luks no lvm.

**Comment by illiliti** [comment]
Which luks version do you use(LUKS1 or LUKS2)? Can you try to boot with kernel parameter `break=luks` and manually unlock luks with `--debug`?

**Comment by illiliti** [comment]
Also, your processor is AMD Ryzen?

**Comment by muevoid** [comment]
I will attempt that in a little bit in pc I can answer the other two questions though. Pretty sure luk2 and no ive had it working on this pc before last time I installed kiss not sure what changed.

**Comment by illiliti** [comment]
Json-c update may be related to this issue
https://bbs.archlinux.org/viewtopic.php?id=255283
https://gitlab.com/cryptsetup/cryptsetup/-/issues/558
https://github.com/json-c/json-c/issues/588

**Comment by muevoid** [comment]
Ah I think that may be it I do have discards enabled I will try re making tinyramfs with no discards

**Comment by illiliti** [comment]
Well..Did you resolve this issue?

**Comment by illiliti** [comment]
Fixed
